apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo
  labels:
    app: demo-service
    service: demo-service
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: demo-service